import { notFound } from 'next/navigation'
import { DemoBanner } from '@/components/DemoBanner'
import { StatusPill } from '@/components/StatusPill'
import { demoStore } from '@/lib/demo/store'

export default async function DocumentPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params; const doc=demoStore().documents.find(x=>x.publicToken===token); if(!doc) notFound()
  return <><DemoBanner/><section className="section card"><div className="eyebrow">DOCUMENTCHASER · SECURE LINK</div><h1>{doc.title}</h1><p>Requested from: <strong>{doc.requestedFrom}</strong></p><p>Why: {doc.reason}</p><p>Due: {new Date(doc.dueAt).toLocaleString('en-GB')}</p><StatusPill label={doc.status} tone={doc.status==='ACCEPTED'||doc.status==='VERIFIED'?'good':doc.status==='EXPIRED'||doc.status==='REJECTED'?'bad':'warn'}/></section><section className="section grid-2"><div className="card"><h2>Lifecycle</h2><div className="timeline">{['REQUESTED','OPENED','UPLOADED','RECEIVED','VALIDATING','VALIDATED','VERIFIED','ACCEPTED'].map((s,i)=><div className="timeline-item" key={s}><div>{s}</div><div>{doc.status===s?<StatusPill label="CURRENT" tone="good"/>:i < ['REQUESTED','OPENED','UPLOADED','RECEIVED','VALIDATING','VALIDATED','VERIFIED','ACCEPTED'].indexOf(doc.status)?<span className="muted">Completed in a prior step</span>:<span className="muted">Not reached</span>}</div></div>)}</div></div><div className="card"><h2>Submission boundary</h2><p className="muted">A document can be uploaded without proving its contents are true. Validation checks basic structure/security; verification is a separate evidence-backed decision.</p>{doc.fileName && <div className="success"><strong>Artifact received:</strong> {doc.fileName}<br/>Hash recorded: {doc.artifactHash}</div>}<div className="actions"><a className="btn" href={`/api/demo/document?token=${token}`}>Inspect simulated document state</a></div></div></section></>
}
