const assert = require('node:assert/strict')
const { canTransitionPayment, canTransitionTransaction, obligationStatus } = require('../.tmp/core/domain/state-machine.js')
const { evaluateRisk } = require('../.tmp/core/domain/risk.js')
const { authorizeHighImpact } = require('../.tmp/core/domain/governance.js')
const { createAccountChangeEvent } = require('../.tmp/core/domain/account-shield.js')

assert.equal(canTransitionPayment('PAYMENT_EVIDENCE_SUBMITTED','PAYMENT_VERIFIED'), false)
assert.equal(canTransitionPayment('PAYMENT_PROCESSOR_CONFIRMED','PAYMENT_VERIFIED'), true)
assert.equal(canTransitionTransaction('DRAFT','COMPLETE'), false)
assert.equal(obligationStatus(undefined,undefined,new Date('2026-09-18T00:00:00Z')), 'UNKNOWN')
const risk = evaluateRisk({duplicateReference:false,replayedEvent:true,amountMismatch:true,destinationMismatch:false,failedAttempts:0,accountChangedRecently:true,highValueFirstUse:false,repeatedDisputes:false,providerAnomaly:false}, '2026-09-18T00:00:00Z')
assert.equal(risk.state, 'STEP_UP')
assert.ok(risk.events.some(e=>e.code==='AMOUNT_MISMATCH'))
assert.equal(authorizeHighImpact({identity:true,authority:true,policy:true,evidence:false,riskClass:'R4'}).allowed, false)
assert.equal(authorizeHighImpact({identity:true,authority:true,policy:true,evidence:true,riskClass:'R4'}).allowed, true)
const change = createAccountChangeEvent({oldDestination:'acct-old',newDestination:'acct-new',initiator:'merchant'})
assert.equal(change.outcome, 'STEP_UP_REQUIRED')
console.log('Core smoke tests passed: transaction/payment/risk/governance/account-shield.')
